### ISSUE TITLE
uninitialized constant #<Class:RuboCop::Changed::Commands>::Rubocop

### ISSUE THREAD

**Issue by maysam** [dukaev/rubocop-changed#2]
doesn't work with ruby 3 rails 7

**Comment by dukaev** [comment]
Hello!
Thank you for issue.
Could you send output:
```bash
ruby -v
bundle exec rails -v
bundle exec rubocop -v
```

**Comment by maysam** [comment]
Thanks for checking

```
ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [arm64-darwin23]
Rails 7.1.1
1.57.1
```

**Comment by dukaev** [comment]
Hello @maysam!
Please, could try to reproduce error with the latest update `rubocop-changed (0.0.4)`

**Comment by maysam** [comment]
@dukaev 

here you go

```
Fetching rubocop-changed 0.0.4 (was 0.0.3)
Installing rubocop-changed 0.0.4 (was 0.0.3)
Bundle updated!
maysam@maysams-MBP hesabketab % rubocop    
Unknown error. Please, create issue on https://github.com/dukaev/rubocop-changed/issues.
Command:
git symbolic-ref refs/remotes/origin/HEAD
Output:
fatal: ref refs/remotes/origin/HEAD is not a symbolic ref


/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-changed-0.0.4/lib/rubocop/changed/commands.rb:67:in `run'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-changed-0.0.4/lib/rubocop/changed/commands.rb:59:in `default_branch'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-changed-0.0.4/lib/rubocop/changed/commands.rb:36:in `compared_branch'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-changed-0.0.4/lib/rubocop/changed/commands.rb:19:in `changed_files'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-changed-0.0.4/lib/rubocop/changed/files.rb:9:in `call'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-changed-0.0.4/lib/rubocop/target_finder.rb:9:in `glob'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.60.2/lib/rubocop/target_finder.rb:93:in `find_files'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.60.2/lib/rubocop/target_finder.rb:59:in `target_files_in_dir'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.60.2/lib/rubocop/target_finder.rb:32:in `find'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.60.2/lib/rubocop/runner.rb:111:in `find_target_files'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.60.2/lib/rubocop/runner.rb:68:in `run'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.60.2/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.60.2/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.60.2/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.60.2/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.60.2/lib/rubocop/cli/command.rb:11:in `run'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.60.2/lib/rubocop/cli/environment.rb:18:in `run'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.60.2/lib/rubocop/cli.rb:118:in `run_command'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.60.2/lib/rubocop/cli.rb:125:in `execute_runners'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.60.2/lib/rubocop/cli.rb:51:in `block in run'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.60.2/lib/rubocop/cli.rb:77:in `profile_if_needed'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.60.2/lib/rubocop/cli.rb:43:in `run'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.60.2/exe/rubocop:19:in `block in <top (required)>'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/3.0.0/benchmark.rb:308:in `realtime'
/Users/maysam/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.60.2/exe/rubocop:19:in `<top (required)>'
/Users/maysam/.rbenv/versions/3.0.6/bin/rubocop:25:in `load'
/Users/maysam/.rbenv/versions/3.0.6/bin/rubocop:25:in `<main>'
```

**Comment by dukaev** [comment]
The command `git symbolic-ref refs/remotes/origin/HEAD` is used to check which branch is the default branch for the remote repository, typically origin. However, the error message "fatal: ref refs/remotes/origin/HEAD is not a symbolic ref" indicates that this reference does not exist as a symbolic reference in your local Git repository.

**Comment by maysam** [comment]
I'm using to remotes named origin and gitlab
but shouldn't the tool not expect defaults? and work on current changes?
